included:
    - Sources
    - Tests

disabled_rules: # rule identifiers to exclude from running
    - function_body_length
    - type_body_length
    - file_length

trailing_comma:
    mandatory_comma: true

nesting:
    type_level: 2

opt_in_rules:
    - closure_end_indentation
    - literal_expression_end_indentation

identifier_name:
    allowed_symbols:
        - "_"
    min_length: 2
    max_length:
        warning: 90
        error: 1000
    excluded:
        - id
        - or

type_name:
    min_length: 3
    max_length:
        warning: 90
        error: 1000
    allowed_symbols:
        - "_"
    excluded:
        - ID

